# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userask',
            old_name='work_position',
            new_name='course_name',
        ),
        migrations.RemoveField(
            model_name='userask',
            name='points',
        ),
    ]
